### ISSUE TITLE
Redirect URL doesn't work when signing in with Google

### ISSUE THREAD

**Issue by pflugs30** [okta-samples/okta-react-sample#118]
I followed [the SPA tutorial](https://developer.okta.com/docs/guides/sign-into-spa-redirect/react/main/#next-steps) and found my way to this repo.  After setting up my org with a new Okta developer account and creating the application, I was able to start this sample code.  When I tried to login with Google, however, the app didn't redirect properly.  When logged in using my Okta developer email and password, the sample app correctly redirects from the Okta signin widget to the sample app.

Here were my exact steps:
1. Install Okta CLI.
2. Create new Okta Developer account by signing in with a Google Account.
3. Set up Okta Developer account password by clicking link in the welcome email.
4. Clone this sample project and install dependencies.
5. Run sample project and click Login.
6. At the Okta signin widget, click **Need help signing in?** and then **Sign in with Google**.
7. Choose (or sign in with) the Google account used for the Okta Developer account.
8. The Okta signin widget will then redirect into the Okta Developer account admin portal.

In order to sign into the sample app, I need to:
1. Type the sample app URL into my browser address bar.
2. Click **Login**.
3. The sample app will eventually redirect from the login to the login callback route to the sample app homepage, and I will be logged in.

I would have expected the widget to redirect me back to the sample app running locally.  Is there a configuration I need to change?  Thanks for your help!

**Comment by mraible** [comment]
I believe this is an issue that happens when you create your account with a social provider like GitHub or Google. I'd recommend creating a new user in your Okta org and using those credentials to test your app's authentication flow.

**Comment by pflugs30** [comment]
Hi @mraible!  Thanks for the prompt response.  Much appreciated.

I can confirm that when I create a new User in my Org (or use the Developer Admin account with its email and password), I'm able to sign in to the sample app running locally.

I was hoping there would be some setting I could change either in the Okta Org admin pages or in the code where authentication with a Social Provider would redirect correctly.

**Comment by pflugs30** [comment]
However, as I think further, Social Login is not critical to my needs at this time.  I'm working with the sample app to get familiar with adding Okta to a React app (specifically, [Mozilla Hubs](https://github.com/mozilla/hubs/)).  Once I do, my client will want the Users to authenticate via SAML against a specific AD group membership, so I don't really need to figure this out right now.

I simply wanted to report it in case someone Googles it in the future.  Thanks again!

**Comment by mraible** [comment]
If you want to add social login, you'll need to customize the hosted Sign-In Widget. This tutorial shows how:

https://developer.okta.com/blog/2020/09/21/ionic-apple-google-signin

Since it was published, things have gotten easier. We allow you to create custom domains and certificates with Let's Encrypt now.
